project_id = "aqjcouhyaxtmfruqcgzf"

[functions.sitemap]
verify_jwt = false

[functions.sitemap-static]
verify_jwt = false

[functions.sitemap-inventory]
verify_jwt = false

[functions.indexnow]
verify_jwt = false

[functions.send-email]
verify_jwt = false
